#!/bin/bash

echo "Executing iptables rules for tracking NSIS packets"

sudo iptables -N FORWARD_UDP
sudo iptables -A FORWARD -p udp -s 0/0 -j FORWARD_UDP
sudo iptables -N natfwd_filter
sudo iptables -A FORWARD ! -p udp -s 0/0 -j natfwd_filter
sudo iptables -A FORWARD_UDP -p udp --sport 270 -j NFQUEUE --queue-num 0
sudo iptables -A FORWARD_UDP -p udp ! --sport 270 -j natfwd_filter


